"""modified the id to faculties model

Revision ID: 01a93ca965f5
Revises: 5cb30c6f67c9
Create Date: 2024-02-18 11:35:10.369660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a93ca965f5'
down_revision = '5cb30c6f67c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculties', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['id'], ['id'])

    # ### end Alembic commands ###
